;; Answer

(load "./ex3_21.scm")

(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (insert-queue! item)
      (let ((new-pair (cons item '())))
        (cond ((null? front-ptr)
               (set! front-ptr new-pair)
               (set! rear-ptr new-pair)
               (cons front-ptr rear-ptr))
              (else
                (set-cdr! rear-ptr new-pair)
                (set! rear-ptr new-pair)
                (cons front-ptr rear-ptr)))))
    (define (delete-queue!)
      (cond ((null? front-ptr)
             (error "DELETE! called with an empty queue" (cons front-ptr rear-ptr)))
            (else (set! front-ptr (cdr front-ptr))
                  (cons front-ptr rear-ptr))))
    (define (dispatch m)
      (cond
        ((eq? m 'front-ptr) front-ptr)
        ((eq? m 'rear-ptr) rear-ptr)
        ((eq? m 'empty?) (null? front-ptr))
        ((eq? m 'front-queue)
         (if (null? front-ptr)
           (error "FRONT called with an empty queue" (cons front-ptr rear-ptr))
           (car front-ptr)))
        ((eq? m 'insert) insert-queue!)
        ((eq? m 'delete) delete-queue!)))
    dispatch))
