;; Answer

(define (make-account balance pass)
  (define alarm 0)
  (define (call-the-cops) "Call the cops")
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (if (eq? p pass)
      (begin
        (set! alarm 0)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request: MAKE-ACCOUNT" m))))
      (lambda (amount)
        (set! alarm (+ 1 alarm))
        (if (> alarm 7)
          (call-the-cops)
          "Incorrect password"))))
  dispatch)
